### ISSUE TITLE
There seems to be a problem with the compilation

### ISSUE THREAD

**Issue by LuckyFishGeek** [Niximkk/fuck-nemo#3]
![Snipaste_2024-05-16_17-10-28](https://github.com/Niximkk/fuck-nemo/assets/29472751/6863f4f8-d5d6-4e30-a584-44e70a7af596)

All dependencies have been installed

error code : no matching function for call to 'm5gfx::M5GFX::drawBmp(const short unsigned int [32400], int)'

**Comment by Niximkk** [comment]
You did something wrong, try following this tutorial:
https://discord.com/invite/d8dHNh5F74
(If discord is banned on your country use a VPN, or else womp womp.)

**Comment by LuckyFishGeek** [comment]
> You did something wrong, try following this tutorial: https://discord.com/invite/d8dHNh5F74 (If discord is banned on your country use a VPN, or else womp womp.)

I've done everything inside the link you sent before compiling it
